const {test}=require('node:test');
const assert=require('node:assert/strict');
const {database}=require('../scripts/database-fixture');
test('migrations from empty database: private history, immutable code, atomic writes and optimistic conflict', async t=>{
  const db=await database(); t.after(()=>db.close());
  const actor='00000000-0000-4000-8000-000000000001';
  await db.exec(`insert into auth.users values('${actor}','test@example.test'); insert into public.plate_access("userId") values('${actor}');`);
  const client=(await db.query("insert into clients(name) values('Test') returning id")).rows[0].id;
  await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${actor}',false);`);
  const plate=(await db.query('insert into plates("clientId",status,"destinationUrl") values($1,$2,$3) returning code,revision',[client,'active','https://example.test/a'])).rows[0];
  assert.equal(plate.revision,0);
  await db.query('update plates set "destinationUrl"=$1 where code=$2 and revision=$3',['https://example.test/b',plate.code,0]);
  const conflict=await db.query('update plates set "destinationUrl"=$1 where code=$2 and revision=$3 returning code',['https://example.test/c',plate.code,0]);
  assert.equal(conflict.rows.length,0);
  const history=(await db.query('select * from plate_destination_history where "plateCode"=$1 order by revision',[plate.code])).rows;
  assert.equal(history.length,2); assert.equal(history[1].previousUrl,'https://example.test/a');assert.equal(history[1].destinationUrl,'https://example.test/b');assert.equal(history[1].actorId,actor);
  await db.query('update plates set "destinationUrl"=$1 where code=$2',['https://example.test/b',plate.code]);
  assert.equal((await db.query('select count(*)::int as n from plate_destination_history')).rows[0].n,2);
  await assert.rejects(db.query('update plates set code=$1 where code=$2',['PL-999999',plate.code]));
  await assert.rejects(db.query('delete from plate_destination_history'));
  await assert.rejects(db.query('insert into plate_destination_history("plateCode","destinationUrl","actorType",revision) values($1,$2,$3,$4)',[plate.code,'https://fake.test','system',999]));
  await db.exec('reset role');
  await db.exec(`create function private.reject_history_test() returns trigger language plpgsql as $$begin raise exception 'test history failure';end$$;
    create trigger reject_history_test before insert on plate_destination_history for each row execute function private.reject_history_test();`);
  await db.exec(`set role authenticated;`);
  await assert.rejects(db.query('update plates set "destinationUrl"=$1 where code=$2',['https://example.test/c',plate.code]));
  assert.equal((await db.query('select "destinationUrl" from plates where code=$1',[plate.code])).rows[0].destinationUrl,'https://example.test/b');
  await db.exec("select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',false)");
  assert.equal((await db.query('select * from clients')).rows.length,0);
  await assert.rejects(db.query("insert into clients(name) values('Unauthorized')"));
  await db.exec('reset role;set role anon');
  assert.equal((await db.query('select code,active,"destinationUrl" from plates')).rows.length,1);
  await assert.rejects(db.query('select "clientId" from plates'));
  await assert.rejects(db.query('select * from plate_destination_history'));
});

test('analytics counts valid access only, protects private events, survives retention and fails open',async t=>{
 const db=await database();t.after(()=>db.close());
 const actor='00000000-0000-4000-8000-000000000003';
 await db.exec(`insert into auth.users values('${actor}','analytics@example.test');insert into plate_access("userId") values('${actor}');`);
 const client=(await db.query("insert into clients(name) values('Analytics') returning id")).rows[0].id;
 const code=(await db.query('insert into plates("clientId",status,"destinationUrl") values($1,$2,$3) returning code',[client,'active','https://example.test'])).rows[0].code;
 await db.exec('set role anon');
 assert.equal((await db.query('select * from resolve_plate_access($1,true)',[code])).rows[0].recorded,true);
 assert.equal((await db.query('select * from resolve_plate_access($1,false)',[code])).rows[0].recorded,false);
 assert.equal((await db.query("select * from resolve_plate_access('PL-999999',true)")).rows.length,0);
 await assert.rejects(db.query('select * from plate_scan_events'));
 await assert.rejects(db.query('insert into plate_scan_daily("plateCode",day,count) values($1,current_date,999)',[code]));
 await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${actor}',false);`);
 let summary=(await db.query('select plate_scan_summary($1) as stats',[code])).rows[0].stats;
 assert.deepEqual([summary.today,summary.days7,summary.days30,summary.total],[1,1,1,1]);
 await db.exec('reset role');
 await db.query('update plate_scan_events set "occurredAt"=now()-interval \'31 days\'');
 await db.query('select private.prune_plate_scans()');
 assert.equal((await db.query('select count(*)::int n from plate_scan_events')).rows[0].n,0);
 assert.equal((await db.query('select sum(count)::int n from plate_scan_daily')).rows[0].n,1);
 await db.exec(`create function private.reject_scan_test() returns trigger language plpgsql as $$begin raise exception 'scan unavailable';end$$;create trigger reject_scan_test before insert on plate_scan_daily for each row execute function private.reject_scan_test();set role anon;`);
 const resolved=(await db.query('select * from resolve_plate_access($1,true)',[code])).rows[0];
 assert.equal(resolved.destinationUrl,'https://example.test');assert.equal(resolved.recorded,false);
 await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from plate_scan_events')).rows[0].n,0);
 await db.query('update plates set status=$1 where code=$2',['inactive',code]);
 await db.exec('set role anon');assert.equal((await db.query('select * from resolve_plate_access($1,true)',[code])).rows[0].recorded,false);
});
