const {test}=require('node:test');const assert=require('node:assert/strict');const {database}=require('../scripts/database-fixture');const {restoreFixture}=require('../scripts/restore-fixture');
test('reports reconcile with known sales, exclude cancelled, use BR dates and restore application snapshot',async t=>{
 const db=await database();t.after(()=>db.close());const actor='00000000-0000-4000-8000-000000000001';await db.exec(`insert into auth.users values('${actor}','test@example.test');insert into plate_access("userId") values('${actor}');set role authenticated;select set_config('request.jwt.claim.sub','${actor}',false)`);
 const client=(await db.query("insert into clients(name) values('Cliente') returning id")).rows[0].id;const product=(await db.query('insert into products(name,"generatesPlate") values($1,true) returning id',['Placa'])).rows[0].id;
 const items=JSON.stringify([{productId:product,quantity:2,priceCents:12990,discountCents:980}]);const sale='00000000-0000-4000-8000-000000000002',cancelled='00000000-0000-4000-8000-000000000003';await db.query('select create_sale($1,$2,$3,$4::jsonb)',[sale,client,'2026-10-05',items]);await db.query('select create_sale($1,$2,$3,$4::jsonb)',[cancelled,client,'2026-10-05',items]);await db.query('select cancel_sale($1,0,$2)',[cancelled,'Cancelada']);
 const item=(await db.query('select id from sale_items where "saleId"=$1',[sale])).rows[0].id;const code=(await db.query('select generate_sale_plate($1,1,$2) code',[item,'https://example.test'])).rows[0].code;await db.query('update plates set status=$1 where code=$2',['active',code]);
 const stage=(await db.query('select id from crm_stages where not "requiresFollowup" order by position limit 1')).rows[0].id;const deal='00000000-0000-4000-8000-000000000004';await db.query('select save_deal($1,null,$2::jsonb,null,$3::uuid[])',[deal,JSON.stringify({clientId:client,name:'Ganha sem compra extra',stageId:stage,result:'won'}),[]]);
 await db.exec("reset role;update deals set \"closedAt\"='2026-10-05T23:59:00-03:00' where id='"+deal+"';alter table clients disable trigger prepare_record;update clients set \"createdAt\"='2026-10-06T02:30:00Z' where id='"+client+"';alter table clients enable trigger prepare_record;set role authenticated");
 const report=(await db.query('select workspace_report($1,$2) data',['2026-10-05','2026-10-05'])).rows[0].data;assert.equal(report.current.confirmedSales,1);assert.equal(report.current.salesCents,25000);assert.equal(report.current.platesSold,2);assert.equal(report.current.purchasingClients,1);assert.equal(report.current.newClients,1);assert.equal(report.current.won,1);assert.equal(report.current.closed,1);assert.equal(report.activePlatesNow,1);assert.equal(report.products[0].salesCents,25000);assert.equal(report.sources[0].confirmedSales,1);assert.equal(report.previousFrom,'2026-10-04');
 await assert.rejects(db.query('select workspace_report($1,$2)',['2026-10-06','2026-10-05']));const backup=(await db.query('select workspace_backup() data')).rows[0].data;assert.equal(backup.format,'ktivar-app-backup');assert.equal(backup.tables.sales.length,2);assert.ok(!JSON.stringify(backup).includes('password'));
 const restored=await database();t.after(()=>restored.close());await restoreFixture(restored,backup);await restored.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${actor}',false)`);const restoredReport=(await restored.query('select workspace_report($1,$2) data',['2026-10-05','2026-10-05'])).rows[0].data;assert.deepEqual(restoredReport.current,report.current);assert.equal(restoredReport.activePlatesNow,1);assert.equal((await restored.query('select "destinationUrl" from plates where code=$1',[code])).rows[0].destinationUrl,'https://example.test');assert.equal((await restored.query('select count(*)::int n from plate_destination_history')).rows[0].n,backup.tables.plate_destination_history.length);
 await db.exec('reset role;set role anon');await assert.rejects(db.query('select workspace_backup()'));await assert.rejects(db.query('select workspace_report($1,$2)',['2026-10-05','2026-10-05']));await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000099',false)`);await assert.rejects(db.query('select workspace_backup()'));await assert.rejects(db.query('select workspace_report($1,$2)',['2026-10-05','2026-10-05']));
});
