const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function registerAdministration(api,supabase,permanentUrl,validateDestination){
 const db=(req,route,options={})=>supabase('/rest/v1/'+route,{token:req.supabaseToken,...options});
 const guard=fn=>async(req,res,next)=>{try{await fn(req,res);}catch(e){next(e);}};
 api.get('/overview',guard(async(req,res)=>res.json(await db(req,'rpc/administration_overview',{method:'POST',body:{}}))));
 api.get('/settings',guard(async(req,res)=>res.json((await db(req,'application_settings?id=eq.1&select=*'))[0])));
 api.patch('/settings',guard(async(req,res)=>{const b=req.body||{};if(b.fallbackUrl!==null&&typeof b.fallbackUrl!=='string')return res.status(400).json({error:'Informe uma URL ou deixe vazio.'});if(!Number.isSafeInteger(b.revision)||b.revision<0)return res.status(428).json({error:'Reabra as configurações.'});let url=null;try{if(b.fallbackUrl)url=validateDestination(b.fallbackUrl,req.get('host'));if(url){const parsed=new URL(url);if(parsed.host===req.get('host')&&/^\/r\//i.test(decodeURIComponent(parsed.pathname)))throw new Error('O fallback não pode apontar para outra placa.');}}catch(e){return res.status(400).json({error:e.message});}const rows=await db(req,`application_settings?${new URLSearchParams({id:'eq.1',revision:`eq.${b.revision}`,select:'*'})}`,{method:'PATCH',body:{fallbackUrl:url},prefer:'return=representation'});if(!rows.length)return res.status(409).json({error:'A configuração mudou. Reabra antes de salvar.'});res.json(rows[0]);}));
 api.post('/plate-batches',guard(async(req,res)=>{if(!uuid.test(req.body?.id)||!Number.isInteger(req.body.quantity)||req.body.quantity<1||req.body.quantity>500)return res.status(400).json({error:'Informe uma quantidade de 1 a 500.'});res.status(201).json(await db(req,'rpc/generate_plate_batch',{method:'POST',body:{p_id:req.body.id,p_quantity:req.body.quantity}}));}));
 api.get('/stock.csv',guard(async(req,res)=>{const lines=['Código;URL permanente'];for(let offset=0;;offset+=500){const rows=await db(req,`plates?${new URLSearchParams({select:'code',status:'eq.stock',order:'code.asc',limit:'500',offset:String(offset)})}`);for(const p of rows)lines.push(`"${p.code}";"${permanentUrl(req,p.code).replaceAll('"','""')}"`);if(rows.length<500)break;}res.attachment('ktivar-estoque.csv').type('text/csv; charset=utf-8').send('\uFEFF'+lines.join('\r\n'));}));
 api.post('/workspace/clients/:id/portal-access',guard(async(req,res)=>{if(!uuid.test(req.params.id)||typeof req.body?.email!=='string'||req.body.email.length>254||!req.body.email.includes('@')||typeof req.body.enabled!=='boolean')return res.status(400).json({error:'Informe o e-mail de uma conta já criada no Supabase Auth.'});await db(req,'rpc/link_client_portal',{method:'POST',body:{p_client:req.params.id,p_email:req.body.email,p_enabled:req.body.enabled}});res.json({ok:true});}));
 api.get('/workspace/clients/:id/portal-access',guard(async(req,res)=>{if(!uuid.test(req.params.id))return res.status(400).json({error:'Cliente inválido.'});res.json(await db(req,`client_portal_access?${new URLSearchParams({select:'userId,createdAt',clientId:`eq.${req.params.id}`})}`));}));
}
module.exports={registerAdministration};
