const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const {randomUUID}=require('node:crypto');let base=process.env.TEST_BASE_URL,cookie='',server;const ids={clients:[],products:[],sales:[],plates:[]};
async function request(route,method='GET',body){const r=await fetch(base+route,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined,redirect:'manual',signal:AbortSignal.timeout(60000)});const saved=r.headers.getSetCookie();if(saved.length)cookie=saved.map(v=>v.split(';')[0]).join('; ');return r;}
async function json(route,method='GET',body){const r=await request(route,method,body);const data=await r.json();assert.ok(r.ok,`${method} ${route}: ${r.status} ${data.error||''}`);return data;}
(async()=>{try{
 if(!base){server=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'3110'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{if(d.toString().includes('online on port'))resolve();});server.once('error',reject);server.once('exit',()=>reject(new Error('Test server exited')));});base='http://127.0.0.1:3110';}
 assert.equal((await request('/reports')).status,302);assert.equal((await request('/api/workspace/backup')).status,401);await json('/api/login','POST',{email:process.env.TEST_EMAIL,password:process.env.TEST_PASSWORD});assert.equal((await request('/reports')).status,200);
 const date=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date()),route=`/api/workspace/reports?from=${date}&to=${date}`;const baseline=await json(route);
 const client=await json('/api/workspace/clients','POST',{name:'TESTE relatório',enabled:true});ids.clients.push(client.id);const product=await json('/api/workspace/products','POST',{name:'TESTE placa relatório',priceCents:12990,generatesPlate:true,enabled:true});ids.products.push(product.id);
 const items=[{productId:product.id,quantity:2,priceCents:12990,discountCents:980}];for(let i=0;i<2;i++){const id=randomUUID();await json('/api/workspace/sales','POST',{id,clientId:client.id,soldAt:date,items});ids.sales.push(id);}await json(`/api/workspace/sales/${ids.sales[1]}/cancel`,'POST',{revision:0,reason:'Teste cancelado'});
 const sale=await json(`/api/workspace/sales/${ids.sales[0]}`),item=sale.items[0];const {code}=await json(`/api/workspace/sale-items/${item.id}/plate`,'POST',{unit:1,destinationUrl:'https://example.com/ktivar-report-test'});ids.plates.push(code);const plate=await json(`/api/plates/${code}`);await json(`/api/plates/${code}`,'PATCH',{...plate,status:'active'});assert.equal((await request(`/r/${code}`)).status,302);
 const report=await json(route);assert.equal(report.current.confirmedSales,baseline.current.confirmedSales+1);assert.equal(report.current.salesCents,baseline.current.salesCents+25000);assert.equal(report.current.platesSold,baseline.current.platesSold+2);assert.equal(report.current.newClients,baseline.current.newClients+1);assert.equal(report.activePlatesNow,baseline.activePlatesNow+1);assert.equal(report.products.find(p=>p.id===product.id).salesCents,25000);assert.equal(report.plateAccesses.find(p=>p.code===code).count,1);
 assert.ok((await json(`/api/workspace/clients?from=${date}&to=${date}`)).items.some(c=>c.id===client.id));const drilldown=await json(`/api/workspace/sales?clientId=${client.id}&status=confirmed&from=${date}&to=${date}`);assert.equal(drilldown.items.length,1);assert.equal(drilldown.items[0].totalCents,25000);assert.equal((await request('/api/workspace/reports?from=2026-10-06&to=2026-10-05')).status,400);
 const response=await request('/api/workspace/backup');assert.equal(response.status,200);assert.match(response.headers.get('content-disposition'),/attachment/);const backup=await response.json();assert.equal(backup.format,'ktivar-app-backup');assert.ok(backup.tables.sales.some(s=>s.id===sale.id));assert.ok(!Object.keys(backup.tables).some(key=>key.startsWith('auth')));
 console.log('PASS reports: real totals, cancelled excluded, exact cents, BR periods, matching drilldown, plate accesses and authorized application export.');
}finally{if(server)server.kill();console.log('CLEANUP_IDS',JSON.stringify(ids));}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
