const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const {randomUUID}=require('node:crypto');let base=process.env.TEST_BASE_URL,cookie='',server;const ids={clients:[],deals:[],activities:[],stages:[]};
async function request(route,method='GET',body){const r=await fetch(base+route,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined,redirect:'manual',signal:AbortSignal.timeout(60000)});const saved=r.headers.getSetCookie();if(saved.length)cookie=saved.map(v=>v.split(';')[0]).join('; ');return r;}
async function json(route,method='GET',body){const r=await request(route,method,body);const data=await r.json();assert.ok(r.ok,`${method} ${route}: ${r.status} ${data.error||''}`);return data;}
(async()=>{try{
 if(!base){server=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'3109'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{if(d.toString().includes('online on port'))resolve();});server.once('error',reject);server.once('exit',()=>reject(new Error('Test server exited')));});base='http://127.0.0.1:3109';}
 await json('/api/login','POST',{email:process.env.TEST_EMAIL,password:process.env.TEST_PASSWORD});const client=await json('/api/workspace/clients','POST',{name:'TESTE CRM',enabled:true,segmentId:(await json('/api/workspace/catalogs/segments')).find(o=>o.enabled).id,sourceId:(await json('/api/workspace/catalogs/sources')).find(o=>o.enabled).id});ids.clients.push(client.id);
 const stage=await json('/api/workspace/catalogs/stages','POST',{name:'TESTE Retorno',requiresFollowup:true,enabled:true,color:'#667085',position:99});ids.stages.push(stage.id);
 const stages=await json('/api/workspace/catalogs/stages'),normal=stages.find(s=>s.enabled&&!s.requiresFollowup);const reasons=await json('/api/workspace/catalogs/loss-reasons');const types=await json('/api/workspace/catalogs/activity-types');const id=randomUUID();let values={id,clientId:client.id,name:'TESTE oportunidade',estimatedCents:40000,stageId:stage.id,result:'open',tags:[]};
 assert.equal((await request('/api/workspace/deals','POST',values)).status,400);const date=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date());values.nextAction={name:'TESTE contato seguinte',dueDate:date,typeId:types.find(t=>t.enabled).id};await json('/api/workspace/deals','POST',values);ids.deals.push(id);
 let deal=await json(`/api/workspace/deals/${id}`);assert.equal(deal.stageId,stage.id);let next=deal.activities.find(a=>a.isNextAction&&a.enabled&&!a.completedAt);ids.activities.push(next.id);assert.equal(next.name,values.nextAction.name);
 assert.equal((await request(`/api/workspace/deals/${id}`,'PATCH',{...values,revision:99})).status,409);assert.equal((await request(`/api/workspace/deals/${id}`,'PATCH',{...values,revision:deal.revision,result:'lost'})).status,400);
 await json(`/api/workspace/activities/${next.id}/complete`,'POST',{revision:next.revision});assert.equal((await request(`/api/workspace/deals/${id}`,'PATCH',{...values,revision:deal.revision})).status,409);
 deal=await json(`/api/workspace/deals/${id}`);await json(`/api/workspace/deals/${id}`,'PATCH',{...values,revision:deal.revision,stageId:normal.id,result:'won',nextAction:null});assert.equal((await json(`/api/workspace/sales?clientId=${client.id}`)).items.length,0);
 deal=await json(`/api/workspace/deals/${id}`);await json(`/api/workspace/deals/${id}`,'PATCH',{...values,revision:deal.revision,stageId:normal.id,result:'lost',lossReasonId:reasons.find(r=>r.enabled).id,nextAction:null});
 const activityId=randomUUID();await json('/api/workspace/activities','POST',{id:activityId,clientId:client.id,dealId:id,typeId:types.find(t=>t.enabled).id,name:'TESTE follow-up manual',dueDate:date,note:'Nota interna de teste',enabled:true});ids.activities.push(activityId);let activity=await json(`/api/workspace/activities/${activityId}`);assert.ok((await json(`/api/workspace/activities?clientId=${client.id}&mode=today`)).items.some(a=>a.id===activityId));await json(`/api/workspace/activities/${activityId}/complete`,'POST',{revision:activity.revision});assert.ok(!(await json(`/api/workspace/activities?clientId=${client.id}&mode=pending`)).items.some(a=>a.id===activityId));
 const timeline=await json(`/api/workspace/clients/${client.id}/timeline`);assert.equal(new Set(timeline.items.map(e=>e.id)).size,timeline.items.length);assert.ok(timeline.items.some(e=>e.kind==='deals'&&e.actorEmail===process.env.TEST_EMAIL));assert.ok(timeline.items.some(e=>e.kind==='activities'));assert.equal((await json(`/api/workspace/deals/${id}`)).result,'lost');
 console.log('PASS CRM: persistent stages, return/loss validation, stale conflict, single next-action source, completion, dates, no invented sale and private timeline.');
}finally{if(server)server.kill();console.log('CLEANUP_IDS',JSON.stringify(ids));}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
