-- Expose only invoker RPC wrappers. Privileged implementations stay in an unexposed schema.
alter function public.cancel_sale(uuid,bigint,text) set schema private;
revoke all on function private.cancel_sale(uuid,bigint,text) from public,anon;grant execute on function private.cancel_sale(uuid,bigint,text) to authenticated;
create function public.cancel_sale(p_id uuid,p_revision bigint,p_reason text) returns void language sql volatile security invoker set search_path='' as $$select private.cancel_sale(p_id,p_revision,p_reason)$$;
revoke all on function public.cancel_sale(uuid,bigint,text) from public,anon;grant execute on function public.cancel_sale(uuid,bigint,text) to authenticated;
alter function public.complete_activity(uuid,bigint) set schema private;
revoke all on function private.complete_activity(uuid,bigint) from public,anon;grant execute on function private.complete_activity(uuid,bigint) to authenticated;
create function public.complete_activity(p_id uuid,p_revision bigint) returns void language sql volatile security invoker set search_path='' as $$select private.complete_activity(p_id,p_revision)$$;
revoke all on function public.complete_activity(uuid,bigint) from public,anon;grant execute on function public.complete_activity(uuid,bigint) to authenticated;
alter function public.create_sale(uuid,uuid,date,jsonb) set schema private;
revoke all on function private.create_sale(uuid,uuid,date,jsonb) from public,anon;grant execute on function private.create_sale(uuid,uuid,date,jsonb) to authenticated;
create function public.create_sale(p_id uuid,p_client uuid,p_date date,p_items jsonb) returns uuid language sql volatile security invoker set search_path='' as $$select private.create_sale(p_id,p_client,p_date,p_items)$$;
revoke all on function public.create_sale(uuid,uuid,date,jsonb) from public,anon;grant execute on function public.create_sale(uuid,uuid,date,jsonb) to authenticated;
alter function public.generate_sale_plate(uuid,integer,text) set schema private;
revoke all on function private.generate_sale_plate(uuid,integer,text) from public,anon;grant execute on function private.generate_sale_plate(uuid,integer,text) to authenticated;
create function public.generate_sale_plate(p_item uuid,p_unit integer,p_destination text) returns text language sql volatile security invoker set search_path='' as $$select private.generate_sale_plate(p_item,p_unit,p_destination)$$;
revoke all on function public.generate_sale_plate(uuid,integer,text) from public,anon;grant execute on function public.generate_sale_plate(uuid,integer,text) to authenticated;
alter function public.link_sale_deal(uuid,uuid,bigint) set schema private;
revoke all on function private.link_sale_deal(uuid,uuid,bigint) from public,anon;grant execute on function private.link_sale_deal(uuid,uuid,bigint) to authenticated;
create function public.link_sale_deal(p_sale uuid,p_deal uuid,p_revision bigint) returns void language sql volatile security invoker set search_path='' as $$select private.link_sale_deal(p_sale,p_deal,p_revision)$$;
revoke all on function public.link_sale_deal(uuid,uuid,bigint) from public,anon;grant execute on function public.link_sale_deal(uuid,uuid,bigint) to authenticated;
alter function public.operator_list() set schema private;
revoke all on function private.operator_list() from public,anon;grant execute on function private.operator_list() to authenticated;
create function public.operator_list() returns table(id uuid,email text) language sql stable security invoker set search_path='' as $$select * from private.operator_list()$$;
revoke all on function public.operator_list() from public,anon;grant execute on function public.operator_list() to authenticated;
alter function public.save_activity(uuid,bigint,jsonb) set schema private;
revoke all on function private.save_activity(uuid,bigint,jsonb) from public,anon;grant execute on function private.save_activity(uuid,bigint,jsonb) to authenticated;
create function public.save_activity(p_id uuid,p_revision bigint,p_data jsonb) returns uuid language sql volatile security invoker set search_path='' as $$select private.save_activity(p_id,p_revision,p_data)$$;
revoke all on function public.save_activity(uuid,bigint,jsonb) from public,anon;grant execute on function public.save_activity(uuid,bigint,jsonb) to authenticated;
alter function public.save_deal(uuid,bigint,jsonb,jsonb,uuid[]) set schema private;
revoke all on function private.save_deal(uuid,bigint,jsonb,jsonb,uuid[]) from public,anon;grant execute on function private.save_deal(uuid,bigint,jsonb,jsonb,uuid[]) to authenticated;
create function public.save_deal(p_id uuid,p_revision bigint,p_data jsonb,p_next jsonb,p_tags uuid[]) returns uuid language sql volatile security invoker set search_path='' as $$select private.save_deal(p_id,p_revision,p_data,p_next,p_tags)$$;
revoke all on function public.save_deal(uuid,bigint,jsonb,jsonb,uuid[]) from public,anon;grant execute on function public.save_deal(uuid,bigint,jsonb,jsonb,uuid[]) to authenticated;
alter function public.set_client_tags(uuid,uuid[]) set schema private;
revoke all on function private.set_client_tags(uuid,uuid[]) from public,anon;grant execute on function private.set_client_tags(uuid,uuid[]) to authenticated;
create function public.set_client_tags(p_client uuid,p_tags uuid[]) returns void language sql volatile security invoker set search_path='' as $$select private.set_client_tags(p_client,p_tags)$$;
revoke all on function public.set_client_tags(uuid,uuid[]) from public,anon;grant execute on function public.set_client_tags(uuid,uuid[]) to authenticated;
alter function public.set_primary_contact(uuid) set schema private;
revoke all on function private.set_primary_contact(uuid) from public,anon;grant execute on function private.set_primary_contact(uuid) to authenticated;
create function public.set_primary_contact(p_id uuid) returns void language sql volatile security invoker set search_path='' as $$select private.set_primary_contact(p_id)$$;
revoke all on function public.set_primary_contact(uuid) from public,anon;grant execute on function public.set_primary_contact(uuid) to authenticated;
